### PR TITLE
extracting into footer.php

### PR DESCRIPTION
**Pull request by CobbyElsonfx**

### CODE REVIEW

**Review by Richmond-Andoh — CHANGES_REQUESTED** [review]
Bro I think you should take out those images

**Comment by CobbyElsonfx** [comment]
Alright pls

**Comment by OliverMensahDev** [comment]
Kindly check the code and see which parts have common codes that could be split into a footer.php

**Comment by Richmond-Andoh** [comment]
Sir I think Francis has already done that or

**Comment by Richmond-Andoh** [comment]
Should I check the whole project or only the part relating to the footer?

**Pull request merged**
